"""add_business_data_tables

Revision ID: 2146b5825361
Revises: 001_initial_schema
Create Date: 2025-09-21 00:38:59.127679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2146b5825361'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('assistant_id', sa.String(length=100), nullable=True),
    sa.Column('vapi_call_id', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calls_assistant_status', 'calls', ['assistant_id', 'status'], unique=False)
    op.create_index('idx_calls_created_at', 'calls', ['created_at'], unique=False)
    op.create_index('idx_calls_customer_phone', 'calls', ['customer_phone'], unique=False)
    op.create_index('idx_calls_outcome', 'calls', ['outcome'], unique=False)
    op.create_index('idx_calls_started_at', 'calls', ['started_at'], unique=False)
    op.create_index('idx_calls_tenant_status', 'calls', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_calls_assistant_id'), 'calls', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_calls_created_at'), 'calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_calls_customer_phone'), 'calls', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_calls_ended_at'), 'calls', ['ended_at'], unique=False)
    op.create_index(op.f('ix_calls_outcome'), 'calls', ['outcome'], unique=False)
    op.create_index(op.f('ix_calls_started_at'), 'calls', ['started_at'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.create_index(op.f('ix_calls_tenant_id'), 'calls', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_calls_updated_at'), 'calls', ['updated_at'], unique=False)
    op.create_index(op.f('ix_calls_vapi_call_id'), 'calls', ['vapi_call_id'], unique=True)
    op.create_table('phone_numbers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('assistant_id', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('vapi_phone_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('setup_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phone_numbers_assistant', 'phone_numbers', ['assistant_id'], unique=False)
    op.create_index('idx_phone_numbers_created_at', 'phone_numbers', ['created_at'], unique=False)
    op.create_index('idx_phone_numbers_tenant_status', 'phone_numbers', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_phone_numbers_assistant_id'), 'phone_numbers', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_created_at'), 'phone_numbers', ['created_at'], unique=False)
    op.create_index(op.f('ix_phone_numbers_phone_number'), 'phone_numbers', ['phone_number'], unique=True)
    op.create_index(op.f('ix_phone_numbers_status'), 'phone_numbers', ['status'], unique=False)
    op.create_index(op.f('ix_phone_numbers_tenant_id'), 'phone_numbers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_updated_at'), 'phone_numbers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_phone_numbers_vapi_phone_id'), 'phone_numbers', ['vapi_phone_id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_limits_created', 'rate_limits', ['created_at'], unique=False)
    op.create_index('idx_rate_limits_key_endpoint', 'rate_limits', ['key', 'endpoint'], unique=False)
    op.create_index('idx_rate_limits_window', 'rate_limits', ['window_start', 'window_end'], unique=False)
    op.create_index(op.f('ix_rate_limits_endpoint'), 'rate_limits', ['endpoint'], unique=False)
    op.create_index(op.f('ix_rate_limits_key'), 'rate_limits', ['key'], unique=False)
    op.create_index(op.f('ix_rate_limits_method'), 'rate_limits', ['method'], unique=False)
    op.create_index(op.f('ix_rate_limits_window_end'), 'rate_limits', ['window_end'], unique=False)
    op.create_index(op.f('ix_rate_limits_window_start'), 'rate_limits', ['window_start'], unique=False)
    op.create_table('clinics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('policies', sa.JSON(), nullable=True),
    sa.Column('vapi_assistant_id', sa.String(length=100), nullable=True),
    sa.Column('assistant_config', sa.JSON(), nullable=True),
    sa.Column('faq_content', sa.Text(), nullable=True),
    sa.Column('faq_filename', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clinics_approved_by', 'clinics', ['approved_by'], unique=False)
    op.create_index('idx_clinics_created_status', 'clinics', ['created_at', 'status'], unique=False)
    op.create_index('idx_clinics_industry_status', 'clinics', ['industry_type', 'status'], unique=False)
    op.create_index('idx_clinics_phone_email', 'clinics', ['phone', 'email'], unique=False)
    op.create_index('idx_clinics_tenant_status', 'clinics', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_clinics_updated_at', 'clinics', ['updated_at'], unique=False)
    op.create_index('idx_clinics_vapi_assistant_id', 'clinics', ['vapi_assistant_id'], unique=False)
    op.create_index(op.f('ix_clinics_email'), 'clinics', ['email'], unique=False)
    op.create_index(op.f('ix_clinics_industry_type'), 'clinics', ['industry_type'], unique=False)
    op.create_index(op.f('ix_clinics_name'), 'clinics', ['name'], unique=False)
    op.create_index(op.f('ix_clinics_phone'), 'clinics', ['phone'], unique=False)
    op.create_index(op.f('ix_clinics_status'), 'clinics', ['status'], unique=False)
    op.create_index(op.f('ix_clinics_tenant_id'), 'clinics', ['tenant_id'], unique=True)
    op.create_index(op.f('ix_clinics_vapi_assistant_id'), 'clinics', ['vapi_assistant_id'], unique=False)
    op.create_table('csrf_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_csrf_tokens_created', 'csrf_tokens', ['created_at'], unique=False)
    op.create_index('idx_csrf_tokens_expires_used', 'csrf_tokens', ['expires_at', 'is_used'], unique=False)
    op.create_index('idx_csrf_tokens_user_expires', 'csrf_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_csrf_tokens_expires_at'), 'csrf_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_csrf_tokens_is_used'), 'csrf_tokens', ['is_used'], unique=False)
    op.create_index(op.f('ix_csrf_tokens_token_hash'), 'csrf_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_csrf_tokens_user_id'), 'csrf_tokens', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('assistant_id', sa.String(length=100), nullable=True),
    sa.Column('call_id', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointment_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointments_clinic_date', 'appointments', ['clinic_id', 'appointment_date'], unique=False)
    op.create_index('idx_appointments_created_at', 'appointments', ['created_at'], unique=False)
    op.create_index('idx_appointments_patient_phone', 'appointments', ['patient_phone'], unique=False)
    op.create_index('idx_appointments_service_type', 'appointments', ['service_type'], unique=False)
    op.create_index('idx_appointments_status_date', 'appointments', ['status', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_time'), 'appointments', ['appointment_time'], unique=False)
    op.create_index(op.f('ix_appointments_assistant_id'), 'appointments', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_appointments_call_id'), 'appointments', ['call_id'], unique=False)
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointments_created_at'), 'appointments', ['created_at'], unique=False)
    op.create_index(op.f('ix_appointments_google_calendar_event_id'), 'appointments', ['google_calendar_event_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_phone'), 'appointments', ['patient_phone'], unique=False)
    op.create_index(op.f('ix_appointments_service_type'), 'appointments', ['service_type'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_appointments_updated_at'), 'appointments', ['updated_at'], unique=False)
    op.create_table('assistants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('vapi_assistant_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=50), nullable=False),
    sa.Column('voice_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assistants_clinic_status', 'assistants', ['clinic_id', 'status'], unique=False)
    op.create_index('idx_assistants_created', 'assistants', ['created_at'], unique=False)
    op.create_index('idx_assistants_name', 'assistants', ['name'], unique=False)
    op.create_index('idx_assistants_tenant_status', 'assistants', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_assistants_updated_at', 'assistants', ['updated_at'], unique=False)
    op.create_index('idx_assistants_vapi_id', 'assistants', ['vapi_assistant_id'], unique=False)
    op.create_index(op.f('ix_assistants_clinic_id'), 'assistants', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_assistants_name'), 'assistants', ['name'], unique=False)
    op.create_index(op.f('ix_assistants_status'), 'assistants', ['status'], unique=False)
    op.create_index(op.f('ix_assistants_tenant_id'), 'assistants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_assistants_vapi_assistant_id'), 'assistants', ['vapi_assistant_id'], unique=True)
    op.create_table('billing_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vapi_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phone_number_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('appointments_booked', sa.Integer(), nullable=False),
    sa.Column('revenue_generated', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_billing_clinic_period', 'billing_records', ['clinic_id', 'billing_period_start'], unique=False)
    op.create_index('idx_billing_created_at', 'billing_records', ['created_at'], unique=False)
    op.create_index('idx_billing_period', 'billing_records', ['billing_period_start', 'billing_period_end'], unique=False)
    op.create_index(op.f('ix_billing_records_billing_period_end'), 'billing_records', ['billing_period_end'], unique=False)
    op.create_index(op.f('ix_billing_records_billing_period_start'), 'billing_records', ['billing_period_start'], unique=False)
    op.create_index(op.f('ix_billing_records_clinic_id'), 'billing_records', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_billing_records_created_at'), 'billing_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_records_tenant_id'), 'billing_records', ['tenant_id'], unique=False)
    op.create_table('file_uploads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('clinic_id', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('secure_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_quarantined', sa.Boolean(), nullable=False),
    sa.Column('quarantine_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_uploads_clinic_status', 'file_uploads', ['clinic_id', 'status'], unique=False)
    op.create_index('idx_file_uploads_hash', 'file_uploads', ['file_hash'], unique=False)
    op.create_index('idx_file_uploads_quarantined', 'file_uploads', ['is_quarantined', 'created_at'], unique=False)
    op.create_index('idx_file_uploads_type_status', 'file_uploads', ['file_type', 'status'], unique=False)
    op.create_index('idx_file_uploads_user_status', 'file_uploads', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_file_uploads_clinic_id'), 'file_uploads', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_file_uploads_file_hash'), 'file_uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_file_uploads_file_type'), 'file_uploads', ['file_type'], unique=False)
    op.create_index(op.f('ix_file_uploads_is_quarantined'), 'file_uploads', ['is_quarantined'], unique=False)
    op.create_index(op.f('ix_file_uploads_secure_filename'), 'file_uploads', ['secure_filename'], unique=True)
    op.create_index(op.f('ix_file_uploads_status'), 'file_uploads', ['status'], unique=False)
    op.create_index(op.f('ix_file_uploads_user_id'), 'file_uploads', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('clinic_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('insurance_provider', sa.String(length=100), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('preferred_communication', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patients_clinic_name', 'patients', ['clinic_id', 'last_name', 'first_name'], unique=False)
    op.create_index('idx_patients_created_at', 'patients', ['created_at'], unique=False)
    op.create_index('idx_patients_email', 'patients', ['email'], unique=False)
    op.create_index('idx_patients_phone', 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_patients_updated_at'), 'patients', ['updated_at'], unique=False)
    op.add_column('audit_logs', sa.Column('clinic_id', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_index('idx_audit_ip', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_id', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_user_id', table_name='audit_logs')
    op.create_index('idx_audit_logs_action_resource', 'audit_logs', ['action', 'resource_type'], unique=False)
    op.create_index('idx_audit_logs_clinic_action', 'audit_logs', ['clinic_id', 'action'], unique=False)
    op.create_index('idx_audit_logs_clinic_created', 'audit_logs', ['clinic_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_created_action', 'audit_logs', ['created_at', 'action'], unique=False)
    op.create_index('idx_audit_logs_ip_created', 'audit_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index('idx_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_clinic_id'), 'audit_logs', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'user_email')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_column('audit_logs', 'description')
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'success')
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(length=255), nullable=False))
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.drop_index('idx_refresh_token_expires', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_jti', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_revoked', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_tenant_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_user_tenant', table_name='refresh_tokens')
    op.drop_constraint('uq_refresh_tokens_jti', 'refresh_tokens', type_='unique')
    op.create_index('idx_refresh_tokens_created_at', 'refresh_tokens', ['created_at'], unique=False)
    op.create_index('idx_refresh_tokens_expires_revoked', 'refresh_tokens', ['expires_at', 'is_revoked'], unique=False)
    op.create_index('idx_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_user_expires', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'tenant_id')
    op.drop_column('refresh_tokens', 'jti')
    op.drop_column('refresh_tokens', 'revoked')
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index('idx_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index('idx_users_tenant_active', 'users', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index('idx_users_tenant_active', table_name='users')
    op.drop_index('idx_users_role_active', table_name='users')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.String(length=50),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'username')
    op.add_column('refresh_tokens', sa.Column('revoked', sa.BOOLEAN(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('jti', sa.VARCHAR(length=255), nullable=False))
    op.add_column('refresh_tokens', sa.Column('tenant_id', sa.VARCHAR(length=255), nullable=False))
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_expires', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_expires_revoked', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_created_at', table_name='refresh_tokens')
    op.create_unique_constraint('uq_refresh_tokens_jti', 'refresh_tokens', ['jti'])
    op.create_index('idx_refresh_token_user_tenant', 'refresh_tokens', ['user_id', 'tenant_id'], unique=False)
    op.create_index('idx_refresh_token_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_token_tenant_id', 'refresh_tokens', ['tenant_id'], unique=False)
    op.create_index('idx_refresh_token_revoked', 'refresh_tokens', ['revoked'], unique=False)
    op.create_index('idx_refresh_token_jti', 'refresh_tokens', ['jti'], unique=False)
    op.create_index('idx_refresh_token_expires', 'refresh_tokens', ['expires_at'], unique=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.drop_column('refresh_tokens', 'is_revoked')
    op.drop_column('refresh_tokens', 'token_hash')
    op.add_column('audit_logs', sa.Column('success', sa.VARCHAR(length=10), nullable=False))
    op.add_column('audit_logs', sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('audit_logs', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('audit_logs', sa.Column('tenant_id', sa.VARCHAR(length=255), nullable=False))
    op.add_column('audit_logs', sa.Column('user_email', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_clinic_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_ip_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_clinic_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_clinic_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action_resource', table_name='audit_logs')
    op.create_index('idx_audit_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_ip', 'audit_logs', ['ip_address'], unique=False)
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'clinic_id')
    op.drop_index(op.f('ix_patients_updated_at'), table_name='patients')
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_index('idx_patients_phone', table_name='patients')
    op.drop_index('idx_patients_email', table_name='patients')
    op.drop_index('idx_patients_created_at', table_name='patients')
    op.drop_index('idx_patients_clinic_name', table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_file_uploads_user_id'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_status'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_secure_filename'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_is_quarantined'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_file_type'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_file_hash'), table_name='file_uploads')
    op.drop_index(op.f('ix_file_uploads_clinic_id'), table_name='file_uploads')
    op.drop_index('idx_file_uploads_user_status', table_name='file_uploads')
    op.drop_index('idx_file_uploads_type_status', table_name='file_uploads')
    op.drop_index('idx_file_uploads_quarantined', table_name='file_uploads')
    op.drop_index('idx_file_uploads_hash', table_name='file_uploads')
    op.drop_index('idx_file_uploads_clinic_status', table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index(op.f('ix_billing_records_tenant_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_created_at'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_clinic_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_billing_period_start'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_billing_period_end'), table_name='billing_records')
    op.drop_index('idx_billing_period', table_name='billing_records')
    op.drop_index('idx_billing_created_at', table_name='billing_records')
    op.drop_index('idx_billing_clinic_period', table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_index(op.f('ix_assistants_vapi_assistant_id'), table_name='assistants')
    op.drop_index(op.f('ix_assistants_tenant_id'), table_name='assistants')
    op.drop_index(op.f('ix_assistants_status'), table_name='assistants')
    op.drop_index(op.f('ix_assistants_name'), table_name='assistants')
    op.drop_index(op.f('ix_assistants_clinic_id'), table_name='assistants')
    op.drop_index('idx_assistants_vapi_id', table_name='assistants')
    op.drop_index('idx_assistants_updated_at', table_name='assistants')
    op.drop_index('idx_assistants_tenant_status', table_name='assistants')
    op.drop_index('idx_assistants_name', table_name='assistants')
    op.drop_index('idx_assistants_created', table_name='assistants')
    op.drop_index('idx_assistants_clinic_status', table_name='assistants')
    op.drop_table('assistants')
    op.drop_index(op.f('ix_appointments_updated_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_type'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_phone'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_google_calendar_event_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_call_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_assistant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_index('idx_appointments_status_date', table_name='appointments')
    op.drop_index('idx_appointments_service_type', table_name='appointments')
    op.drop_index('idx_appointments_patient_phone', table_name='appointments')
    op.drop_index('idx_appointments_created_at', table_name='appointments')
    op.drop_index('idx_appointments_clinic_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_csrf_tokens_user_id'), table_name='csrf_tokens')
    op.drop_index(op.f('ix_csrf_tokens_token_hash'), table_name='csrf_tokens')
    op.drop_index(op.f('ix_csrf_tokens_is_used'), table_name='csrf_tokens')
    op.drop_index(op.f('ix_csrf_tokens_expires_at'), table_name='csrf_tokens')
    op.drop_index('idx_csrf_tokens_user_expires', table_name='csrf_tokens')
    op.drop_index('idx_csrf_tokens_expires_used', table_name='csrf_tokens')
    op.drop_index('idx_csrf_tokens_created', table_name='csrf_tokens')
    op.drop_table('csrf_tokens')
    op.drop_index(op.f('ix_clinics_vapi_assistant_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_tenant_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_status'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_phone'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_name'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_industry_type'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_email'), table_name='clinics')
    op.drop_index('idx_clinics_vapi_assistant_id', table_name='clinics')
    op.drop_index('idx_clinics_updated_at', table_name='clinics')
    op.drop_index('idx_clinics_tenant_status', table_name='clinics')
    op.drop_index('idx_clinics_phone_email', table_name='clinics')
    op.drop_index('idx_clinics_industry_status', table_name='clinics')
    op.drop_index('idx_clinics_created_status', table_name='clinics')
    op.drop_index('idx_clinics_approved_by', table_name='clinics')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_rate_limits_window_start'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_window_end'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_method'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_key'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_endpoint'), table_name='rate_limits')
    op.drop_index('idx_rate_limits_window', table_name='rate_limits')
    op.drop_index('idx_rate_limits_key_endpoint', table_name='rate_limits')
    op.drop_index('idx_rate_limits_created', table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_phone_numbers_vapi_phone_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_updated_at'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_tenant_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_status'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_phone_number'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_created_at'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_assistant_id'), table_name='phone_numbers')
    op.drop_index('idx_phone_numbers_tenant_status', table_name='phone_numbers')
    op.drop_index('idx_phone_numbers_created_at', table_name='phone_numbers')
    op.drop_index('idx_phone_numbers_assistant', table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_calls_vapi_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_updated_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_tenant_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_started_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_outcome'), table_name='calls')
    op.drop_index(op.f('ix_calls_ended_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_customer_phone'), table_name='calls')
    op.drop_index(op.f('ix_calls_created_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_assistant_id'), table_name='calls')
    op.drop_index('idx_calls_tenant_status', table_name='calls')
    op.drop_index('idx_calls_started_at', table_name='calls')
    op.drop_index('idx_calls_outcome', table_name='calls')
    op.drop_index('idx_calls_customer_phone', table_name='calls')
    op.drop_index('idx_calls_created_at', table_name='calls')
    op.drop_index('idx_calls_assistant_status', table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###

